#yaml has a tree like structure , .properties have repeating syntax like datasource

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testDbDEA?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # This option can be 'update', 'validate', 'create', or 'create-drop'
    show-sql: true     # Show SQL statements in the console for debugging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
